import type { Metadata } from 'next'
import '../globals.scss'
import Cabecalho from '@componentes/cabecalho/cabecalho.componente'

export const metadata: Metadata = {
  title: 'Kopp',
  description: 'Generated by create next app'
}

const LISTA_MOCK_ROTAS = [
  {
    rota: '/blitz',
    titulo: 'Modo blitz'
  },
  {
    rota: '/monitoramento',
    titulo: 'Monitoramento'
  }
]

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <Cabecalho rotas={LISTA_MOCK_ROTAS} />
      {children}
    </>
  )
}
