import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'

const montserrat = Montserrat({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
  style: ['normal', 'italic'],
  display: 'swap',
  fallback: ['sans-serif'],
  variable: '--montserrat',
  preload: true
})

export const metadata: Metadata = {
  title: 'Kopp CEK',
  description: 'Generated by create next app',
  manifest: '/manifest.json',
  icons: { apple: '/icon.png' },
  themeColor: '#fff'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='pt-BR'>
      <body className={montserrat.variable}>{children}</body>
    </html>
  )
}
